#!/usr/bin/env python3

print('Enter your name')
name = input()
if name == 'Alice':
    print('Hello Alice')
    quit()
else:
  print('Enter your age')
  age = int(input())
if (age) < 12:
  print('You are not Alice kiddo')
else:
  print ('You are neither Alice nor a kid')

