#!/usr/bin/env python3

# Continue Statement

while True:
    print('Who are you')
    name = input()
    if name != 'joe':
       continue
print('Hello joe password please')
password = input()
if password == 'fish':
print('Acces Granted')

